emulator_web/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from flask import Flask
from flask import render_template
from flask_beaker import BeakerSession
from flask.ext.assets import Environment, Bundle
# from flask_restful import Api, reqparse


session_opts = {
    'session.type': 'ext:memcached',
    'session.cookie_expires': True,
    'session.lock_dir': './data',
    'session.url': '127.0.0.1:11211',
    'session.memcache_module': 'pylibmc',
    'session.auto': True
}


app = Flask(__name__)
app.config.from_object('config')
BeakerSession(app)


@app.errorhandler(404)
def not_found(error):
    return render_template('errors/404.html'), 404


@app.errorhandler(403)
def not_found(error):
    return render_template('errors/403.html'), 403


@app.errorhandler(500)
def not_found(error):
    return render_template('errors/500.html'), 500


# @app.context_processor
# def context_globals():
#     pass


# api = Api(app)
# api_parser = reqparse.RequestParser()


from emulator_web.views import mod as emulator_module
app.register_blueprint(emulator_module)

assets = Environment(app)
js = Bundle('js/app/input.js',
            'js/app/geopolitical/regions.js',
            'js/app/geopolitical/models.js',
            'js/app/emulator_output.js',
            'js/app/emulator_input.js',
            'js/app/emulator_map.js',
            'js/app/emulator_dropzone.js',
            'js/app/emulator_help.js',
            filters='jsmin', output='gen/emulator.js')
assets.register('js_emulator', js)
css = Bundle('css/main.css', filters='cssmin', output='gen/main.css')
assets.register('css_main', css)


if __name__ == '__main__':
    app.run()

emulator_web/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import csv
import itertools
from datetime import datetime

import numpy as np
from flask import render_template, request, Blueprint, jsonify

from emulator import Emulator


mod = Blueprint('emulator', __name__, static_folder='static',
                template_folder='templates')


def do_session(new=False):
    """
    Checks for existence of session data. Writes variables as necessary.
    ...
    Keyword Arguments:
    new: obj
        An Emulator object.
    """
    s = request.environ['beaker.session']
    if new:
        e = new
        s['emulator'] = e
        s.save()
    if 'emulator' not in s:
        e = Emulator()
        s['emulator'] = e
        s.save()
    return s


def page(tpl='index.html'):
    """
    Return HTML for all pages.
    ...
    Args:
        template
    Returns:
        HTML
    """
    now = datetime.now().strftime('%Y%m%d%H%M%S')
    t = render_template(
        tpl,
        now=now,
    )
    return t


@mod.route('/')
def index():
    """Returns index page."""
    do_session()
    return page('index.html')


@mod.route('/documentation')
def documentation():
    """Returns documentation page."""
    do_session()
    return page('documentation/index.html')

@mod.route('/documentation/regions')
def documentation_regions():
    """Returns documentation page."""
    do_session()
    return page('documentation/regions.html')

@mod.route('/rcp/<rcp>/temp/<temp>', methods=['GET', ])
def global_temp_by_model(rcp, temp):
    e = do_session()['emulator']
    return render_template(
        'index.html',
        rcp=rcp,
        temp=temp,
        region_type='global',
    )


@mod.route('/model/<model>/rcp/<rcp>/temp/<temp>', methods=['GET', ])
def regional_temp(model, rcp, temp):
    return render_template(
        'index.html',
        model=model,
        rcp=rcp,
        temp=temp,
    )


@mod.route('/api/model/<model>/rcp/<rcp>/temp/<temp>', methods=['POST', 'GET', ])
def rcp(model, rcp, temp):
    if request.method == 'GET':
        e = do_session()['emulator']
        return jsonify(e.get_model_rcp_output(
            model=model, rcp=rcp, temp=temp
        ))


@mod.route('/api/rcp/<rcp>/temp/<temp>')
def global_mean(rcp, temp):
    if request.method == 'GET':
        e = do_session()['emulator']
        return jsonify(e.get_mean_rcp_output(
            rcp=rcp, temp=temp
        ))


@mod.route('/csv_upload', methods=['POST', 'GET', ])
def csv_upload():
    import StringIO
    def _normalize_newlines(string):
        import re
        return re.sub(r'(\r\n|\r|\n)', '\n', string)

    def split(txt, seps):
        default_sep = seps[0]
        for sep in seps[1:]:
            txt = txt.replace(sep, default_sep)
        return [i.strip() for i in txt.split(default_sep)]

    if request.method == 'POST':
        l = request.files['csv'].stream.readlines()
        l = '\n'.join(l)
        l = _normalize_newlines(l)
        csv_ = csv.reader(StringIO.StringIO(l))
        new_rcp = []
        for c in csv_:
            new_rcp.append(c)
        new_rcp = list(itertools.chain(*new_rcp))
        new_rcp = [float(x) if len(x) > 0 else 0 for x in new_rcp]
        n = len(new_rcp)
        if n == 1:
            new_rcp = new_rcp * 96
        elif n > 96:
            new_rcp = new_rcp[:96]
        elif n < 96:
            new_rcp = np.concatenate(
                (
                    np.array(new_rcp),
                    (np.arange(1, 96 - n + 1) * (new_rcp[-1] - new_rcp[-2])) +
                    new_rcp[-1]
                )
            ).tolist()
        e = do_session()['emulator']
        return jsonify(e.get_model_rcp_output(co2=new_rcp))

emulator_web/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js" lang="en"><!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}RDCEP | Climate Emulator</title>
  {% assets 'css_main' %}<link rel="stylesheet" href="{{ ASSET_URL }}" media="all">{% endassets %}
  <link rel="icon" href="{{ url_for('emulator.static', filename='images/brand/rdcep_logo_16.png') }}">
{#  <script src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=default"></script>#}
  <script src="{{ url_for('static', filename='js/vendor/modernizr-2.6.2.min.js') }}"></script>
  {% include 'google_tracking.html' %}
  {% block headcss %}{% endblock %}
  {% block headjs %}{% endblock %}
</head>
<body>
<!--[if lt IE 7]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<div id=wrapper>
{% block page %}{% endblock %}
</div>

{% block footer %}
{% endblock %}

{% block bodyjs %}
  <script src="/static/js/app/plugins.js"></script>
{% endblock %}
</body>
</html>

emulator_web/templates/base_page.html
{% extends 'base.html' %}
{% block page %}
  <header id="main_nav">
    <nav>
      <ul id="top_nav" class="clearfix">
        <li><a href="{{ url_for('emulator.index') }}"><h1>Climate Emulator</h1></a></li>
        <li><a href=/documentation>Documentation</a></li>
        <li><a href=https://github.com/RDCEP/climate_emulator>Source</a></li>
      </ul>
    </nav>
  </header>

  <article id=main_content class=clearfix>
  {% block content %}
  {% endblock %}
  </article>
  <div id=footer_push></div>
{% endblock %}

{% block footer %}
<div id=footer_wrap>
  <footer id=main_footer>
    <div id=footer_logo>
      <a href="https://www.rdcep.org/">
        <img src="{{ url_for('emulator.static', filename='images/brand/rdcep_logo_60.png') }}" alt>
      </a>
    </div>
    <div id=footer_attribution>
      <h2><a href="https://www.rdcep.org/">RDCEP</a></h2>
      <p>The Climate Emulator is built and maintained by the Center for
        Robust Decision Making on Climate and Energy Policy at the University
        of Chicago. Questions and comments should be directed to
        <a href=mailto:info-rdcep@ci.uchicago.edu>info-rdcep@ci.uchicago.edu</a>.
        </p>
      <p>Funded under NSF Decision Making Under Uncertainty Program.
        Award No. 0951576</p>
    </div>
  </footer>
</div>
{% endblock %}

{% block bodyjs %}
{{ super() }}
{#{% assets 'js_vendor' %}<script src="{{ ASSET_URL }}"></script>{% endassets %}#}
<script src="//cdnjs.cloudflare.com/ajax/libs/dropzone/3.8.4/dropzone.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.4.11/d3.min.js"></script>
<script>
  Options = window.Options || {};
  Options.active_map_region = [];
  Options.active_map_colors = [];
  Options.region_type = {% if region_type %}'{{ region_type }}'{% else %}'regional'{% endif %}; // RCP45,RCP60,RCP85,CUSTOM
  Options.active_rcp = {% if rcp %}'{{ rcp }}'{% else %}'RCP26'{% endif %}; // RCP45,RCP60,RCP85,CUSTOM
  Options.active_model = {% if model %}'{{ model }}'{% else %}'CCSM4'{% endif %}; // 9 others
  Options.temp_type = {% if temp %}'{{ temp }}'{% else %}'relative'{% endif %}; // absolute
</script>
{% assets 'js_emulator' %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{% endblock %}

emulator_web/templates/documentation/index.html
{% extends 'base_page.html' %}
{% block content %}
<section class="text-module" style="padding-bottom: 60px;">

<h2>Documentation</h2>
<h3>Statistical Emulation</h3>
<p>
  Statistical emulation of climate model output involves using a
  ‘training set’ of simulations for each model to fit the parameters
  of a simple statistical model that describes the climate response to
  changing CO<sub>2</sub> concentrations. In the tool here, each region is fit
  separately.</p>
<p>The training set used are archived GCM simulations made as part of the
  <a href="http://cmip-pcmdi.llnl.gov/index.html">Coupled Model
  Intercomparison Project 5 (CMIP5)</a>, and
  archived at the Earth Systems Grid database (available from various
  sites, including <a href="https://www.earthsystemgrid.org/home.htm">here</a>
  or <a href="http://pcmdi9.llnl.gov">here</a>). The simulations use CO<sub>2</sub>
  scenarios developed for the Intergovernmental Panel on Climate Change
  5th Assessment Report. These ‘Representative Concentration
  Pathways’, or RCPs, describe the CO<sub>2</sub> concentrations associated
  with various potential emissions scenarios (Figure 1 below). Where
  available, we use RCP4.5, RCP6.0, and RCP8.5 as the training set.
  For some models that did not archive all scenarios, we use only
  RCP4.5 and RCP8.5.</p>

  <figure>
    <a href="{{ url_for('emulator.static', filename='images/co2_data.png') }}">
      <img src="{{ url_for('emulator.static', filename='images/co2_data.png') }}" alt>
    </a>
    <figcaption>
      CO<sub>2</sub> equivalent atmospheric concentrations for RCP scenarios.
      RCP8.5 represents ‘business-as-usual’. See
      <a href="http://www.pik-potsdam.de/~mmalte/rcps/">http://www.pik-potsdam.de/~mmalte/rcps/</a>
      for further description and data.
    </figcaption>
  </figure>

<p>
  The pre-industrial temeperature for each model is estimated from
  archived ‘historical’ simulations, as the average over
  the first 20 years (1850–1869).</p>
<p>The statistical model used for emulation is described in detail in
  <a href="{{ url_for('emulator.static', filename='files/JCLI-D-13-00099.pdf') }}">Castruccio
  <i>et al</i> 2013</a>, with the only difference here being that we
  simplify the statistical model still further, omitting Castruccio <i>et
  al</i>’s beta1 term.</p>
<p>All code (in Python) and parameters are publicly available through
  our Source page, under an LGPL license.</p>
<p>In plots here, to facilitate comparison across models we normalize
  temperatures for each model and region to the multi-model mean for
  the period 1994–2004. For global temperature, we normalize to the
  NASA-GISS observed 1951–1980 global mean temperature of 14.0 C
  (57.2 F).</p>

<h3>Models and regions</h3>

<p>We are currently emulating 14 models and are in progress on
  extending emulation to all CMIP5 models with sufficient archived
  data.</p>
<p>The current version of the emulation tool can emulate
  BCC-CSM-1.1, CanESM2, CCSM4, CNRM-CM5, GISS-E2-R, GISS-E2-H,
  HadGEM2, IPSL-CM5A-MR, MIROC5, MIROC-ESM-CHEM, MPI-ESM-LR,
  MPI-ESM-MR, MRI-CGCM3, and NorESM. </p>
<p>Of these models, four do not include RCP6.0 (CanESM, CNRM-CM5,
  MPI-ESM-LR, and MPI-ESM-MR).</p>
<p>We are extending the tool to include over 9 additional models:
  ACCESS-1.0, ACCESS-1.3, BNU-ESM, CESM1, CSIRO-Mk3.6.0,
  EC-EARTH, FGOALS, FIO-ESM, and various versions of the GFDL
  model.</p>
<p>Emulation is performed on regions at larger than native model
  resolution. For land areas, regions are chosen to follow national
  borders. Individual regions either lie within a single large country
  or contain groups of smaller countries. For a mapping of regions to
  countries, <a href="{{ url_for('emulator.documentation_regions') }}">see
  this table</a>.</p>

<h3 style="margin:45px 0 15px;font-weight:bold;">Running a user-specified CO<sub>2</sub> scenario</h3>

<p>We have included several scenarios as examples, including three
  for which GCM runs have already been completed and archived.
  However, the real purpose of an emulator is to generate projections
  for scenarios that have not yet been simulated by the larger models.
  Users can generate projections for arbitrary scenarios by uploading a
  text file of CO<sub>2</sub> concentrations.</p>
<p>The file format is a comma-separated list of annual mean CO<sub>2</sub>
  concentrations, in parts per million (ppm), for each year, beginning
  with the year 2005. (For reference, pre-industrial CO<sub>2</sub> was believed
  to be about 270 ppm, and current CO<sub>2</sub> concentration is about 400
  ppm.) The list can be either a row or a column. In most browsers, the
  file can be uploaded simply by dragging over the upload box on the
  webpage. Users with older browsers may have to use the ‘choose
  file’ button.</p>
<p>Once the file is uploaded, the emulation tool will produce plots that
  show emulated model responses to the user-specified CO<sub>2</sub>
  scenario.</p>

<h3 style="margin:45px 0 15px;font-weight:bold;">Future developments</h3>

<p>Planned improvements to the emulator tool include</p>

<ul>
  <li>Making emulation output available as text files</li>
  <li>Adding more models (as described above)</li>
  <li>Plotting GCM output along with emulations, for those scenarios
    where GCM output is available</li>
  <li>Allowing user-controlled y-axis ranges to facilitate comparisons</li>
  <li>Adding maps of temperature changes at any given time</li>
  <li>Adding emulation of short-term climate variability</li>
</ul>

<p>We welcome feedback, and suggestions. Please send comments to
  <a href="mailto:info-rdcep@ci.uchicago.edu">info-rdcep@ci.uchicago.edu</a></p>

<h3 style="margin:45px 0 15px;font-weight:bold;">Developers</h3>

<p>The emulation team includes: Alison Brizius, Stefano Castruccio,
  Robert Jacob, William Leeds, Feifei Liu, Nathan Matteson, John Moosemiller,
  David McInerney, Liz Moyer, Andrew Poppick, Aidan Sakowski,
  Michael Stein, and Grant Wilder</p>
<p>For media inquiries, please contact Rob Mitchum. (773) 484 9890.
  <a href="mailto:rmitchum@uchicago.edu">rmitchum@uchicago.edu</a>.</p>

</section>
{% endblock %}

emulator_web/templates/documentation/regions.html
{% extends 'base_page.html' %}
{% block content %}
<section class="text-module" style="padding-bottom: 60px;">

<h2><a href="{{ url_for('emulator.documentation') }}">Documentation</a></h2>

<h3>Regions and Countries</h3>

<table>
  <tr>
    <th>Region</th>
    <th>Countries</th>
  </tr>
  <tr>
    <td>Middle East</td>
    <td>Afghanistan, Armenia, Azerbaijan, Georgia, Iran, Iraq, Israel, Jordan, Kuwait, Kyrgyzstan, Oman, Pakistan, Qatar, Saudi Arabia, Syria, Tajikistan, Turkmenistan, United Arab Emirates, Uzbekistan, West Bank, Yemen</td>
  </tr>
  <tr>
    <td>Antarctica </td>
    <td>Antarctica, French Southern and Antarctic Lands</td>
  </tr>
  <tr>
    <td>Brazil</td>
    <td>Brazil</td>
  </tr>
  <tr>
    <td>Eastern Canada</td>
    <td>Canada, east of 100th meridian</td>
  </tr>
  <tr>
    <td>Canada West</td>
    <td>Canada, west of 100th meridian</td>
  </tr>
  <tr>
    <td>China</td>
    <td>China</td>
  </tr>
  <tr>
    <td>Southern South America</td>
    <td>Argentina, Bolivia, Chile, Falkland Islands, Paraguay, Uruguay</td>
  </tr>
  <tr>
    <td>Western South America</td>
    <td>Colombia, Ecuador, Peru</td>
  </tr>
  <tr>
    <td>Northern South America</td>
    <td>French Guiana, Guyana, Suriname, Trinidad and Tobago, Venezuela</td>
  </tr>
  <tr>
    <td>Central America</td>
    <td>Belize, Costa Rica, Cuba, Dominican Republic, El Salvador, Guatemala, Haiti, Honduras, Jamaica, Nicaragua, Panama</td>
  </tr>
  <tr>
    <td>Mexico</td>
    <td>Mexico</td>
  </tr>
  <tr>
    <td>Western Europe</td>
    <td>Belgium, Denmark, France, Germany, Ireland, Italy, Netherlands, Portugal, Spain, Switzerland, United Kingdom</td>
  </tr>
  <tr>
    <td>Mongolia</td>
    <td>Mongolia</td>
  </tr>
  <tr>
    <td>Scandinavia</td>
    <td>Finland, Norway, Sweden</td>
  </tr>
  <tr>
    <td>Australia</td>
    <td>Australia, New Caledonia</td>
  </tr>
  <tr>
    <td>Kazakhstan</td>
    <td>Kazakhstan</td>
  </tr>
  <tr>
    <td>Japan</td>
    <td>Japan</td>
  </tr>
  <tr>
    <td>Russia East</td>
    <td>Russia, east of 60th meridian</td>
  </tr>
  <tr>
    <td>Russia West</td>
    <td>Russia, west of 60th meridian</td>
  </tr>
  <tr>
    <td>Asian Isles</td>
    <td>Brunei, Fiji, Indonesia, Malaysia, Papua New Guinea, Philippines, Solomon Islands, Taiwan</td>
  </tr>
  <tr>
    <td>Korean Peninsula </td>
    <td>North Korea, South Korea</td>
  </tr>
  <tr>
    <td>United States East</td>
    <td>United States, east of 100th meridian</td>
  </tr>
  <tr>
    <td>United States West</td>
    <td>United States, west of 100th meridian, excluding Alaska</td>
  </tr>
  <tr>
    <td>Alaska</td>
    <td>United States, Alaska only</td>
  </tr>
  <tr>
    <td>South East Asia</td>
    <td>Bangladesh, Cambodia, East Timor, Laos, Myanmar, Thailand, Vietnam</td>
  </tr>
  <tr>
    <td>Eastern Europe</td>
    <td>Turkey, Albania, Austria, Bosnia and Herzegovina, Bulgaria, Croatia, Czech Republic, Greece, Hungary, Kosovo, Macedonia, Moldova, Montenegro, Republic of Serbia, Romania, Slovakia, Slovenia</td>
  </tr>
  <tr>
    <td>South Africa and Lesotho</td>
    <td>Lesotho, South Africa</td>
  </tr>
  <tr>
    <td>Southern Africa</td>
    <td>Angola, Botswana, Mozambique, Namibia, Swaziland, Zambia, Zimbabwe</td>
  </tr>
  <tr>
    <td>Madagascar</td>
    <td>Madagascar</td>
  </tr>
  <tr>
    <td>India</td>
    <td>Bhutan, India, Nepal, Sri Lanka</td>
  </tr>
  <tr>
    <td>Greenland</td>
    <td>Iceland, Greenland</td>
  </tr>
  <tr>
    <td>North Africa</td>
    <td>Algeria, Egypt, Libya, Morocco, Tunisia, Western Sahara</td>
  </tr>
  <tr>
    <td>New Zealand</td>
    <td>New Zealand</td>
  </tr>
  <tr>
    <td>Western Africa</td>
    <td>Benin, Burkina Faso, Ghana, Guinea, Guinea Bissau, Ivory Coast, Liberia, Mali, Mauritania, Niger, Nigeria, Senegal, Sierra Leone, Togo</td>
  </tr>
  <tr>
    <td>Central Africa</td>
    <td>Burundi, Cameroon, Central African Republic, Chad, Democratic Republic of the Congo, Djibouti, Equatorial Guinea, Eritrea, Ethiopia, Gabon, Kenya, Malawi, Republic of the Congo, Rwanda, Somalia, Somaliland, South Sudan, Sudan, Uganda, United Republic of Tanzania</td>
  </tr>
  <tr>
    <td>North East Europe</td>
    <td>Belarus, Estonia, Latvia, Lithuania, Poland, Ukraine</td>
  </tr>
</table>

</section>
{% endblock %}

emulator_web/templates/index.html
{% extends 'base_page.html' %}
{% block content %}
<section class="text-module" >
  <p>This emulation tool provides statistical representations of the
    behavior of a number of general circulation models (GCMs) from
    different research groups. The emulator is designed to mimic how the
    larger models would have responded, and can provide projections
    of regional temperatures for any user-chosen scenario of future
    CO<sub>2</sub> concentrations.</p>

  <p>The emulator is ‘trained’ on <a href="http://pcmdi9.llnl.gov/" target=_blank>
    publicly-available</a> model simulations of scenarios specified for the
    <a href="http://www.ipcc.ch/report/ar5/" target=_blank>IPCC 5th Assessment
    Report</a>. Users can explore emulated model responses to four IPCC
    scenarios (RCPs 2.6, 4.5, and 8.5) and one scenario of continuous
    exponential growth in CO<sub>2</sub>, or can upload their own
    CO<sub>2</sub> scenarios. Click any of the ‘trajectory’ boxes or drag
    and drop a CO<sub>2</sub> file in the ‘custom’ window. (See
    <a href="{{ url_for('emulator.documentation') }}">documentation</a>
    for instructions and further information.)

  <p style="font-size:.8em;line-height:1.35em;margin-top:1em;">This site is
    currently in beta, and some older browser versions may not support all
    emulator functions. The site works best in Chrome, and Javascript must
    be enabled.</p>

</section>
<div id="emulator">
  <section id="input">
    <h2>
      CO<sub>2</sub> Trajectory (ppm)
    </h2>
    <div id="csv-wrap">
      <form action="{{ url_for('emulator.csv_upload') }}" class="input " id="dz" method="post">
        <p id="dropzone-info" class="dz-message">
          Drop your custom CO<sub>2</sub> data here. <a href id="help-dz" class="help-button">[help]</a>
        </p>
      </form>
    </div>
    <div><h3>CUSTOM</h3><div id="CUSTOM" class="input focused"></div></div>
  </section>
  <section id="output">
    <h2>Projected Temperature Change (&deg;C)&nbsp;
      <span>
        [&nbsp;
        <mark id="relative-temp" class="active">relative</mark>
        &nbsp;|&nbsp;
        <mark id="absolute-temp">absolute</mark>
        &nbsp;]
      </span>
      <img src="{{ url_for('emulator.static', filename='images/app/ajax-loader.gif') }}" alt="AJAX loader" class="ajax-loader">
    </h2>
    <div id="graph"></div>
  </section>
  <section id="models">
    <h2>
      Available climate models
      <span>
        [&nbsp;
        <mark id="regional" class="active">Compare regional data within a model</mark>
        &nbsp;|&nbsp;
        <mark id="global">Compare global means among all models</mark>
        &nbsp;]
      </span>
    </h2>
    <ul class="clearfix">
    </ul>
  </section>
  <section id="map">
    <h2>Select regions to compare</h2>
  </section>
  <footer></footer>
</div>
<div id="help-dz-text" class="help-text">
  <p>"CO2 scenarios should be uploaded as comma-separated (csv) text
    files, containing annual CO<sub>2</sub> concentrations in parts per
    million (ppm) units. The file can contain any number of years, but plots
    will show only through 2100. If fewer than 96 years are listed, the
    scenario will be extrapolated to 2100. See documentation page for further
    information”</p>
</div>
{% endblock %}